services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8440:8440"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    container_name: taskmaster_backend
    command: >
      uvicorn core.asgi:application --host 0.0.0.0 --port 8440
    networks:
      - app_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
      - "8445:443"
    env_file:
      - ./frontend/.env
    environment:
      - REACT_APP_API_URL=/api
      - NODE_ENV=production
    container_name: taskmaster_frontend
    networks:
      - app_net
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=taskmaster
      - POSTGRES_USER=taskmaster_user
      - POSTGRES_PASSWORD=senha_segura_aqui
    networks:
      - app_net

volumes:
  postgres_data:
  static_volume:
  media_volume:
  frontend_node_modules:

networks:
  app_net:
    external: true